//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Addresses = new HashSet<Address>();
            this.AssignedRoles = new HashSet<AssignedRole>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<AssignedRole> AssignedRoles { get; set; }
        public virtual Department Department { get; set; }
    }
}
